Repository aurutils/aurutils, pull requests merged in 2018-12, with the labels that each got.

#459 aur-build: Fix documentation inconsistencies
  man1/aur-build.1
Labels: documentation

#473 aur-search: colorize if stdout is a tty
  lib/aur-search
Labels: (ノಠ益ಠ)ノ彡┻━┻, upstream

#481 Update and sync aur.1
  man1/aur-depends.1
  man1/aur-fetch.1
  man1/aur-graph.1
  man1/aur-pkglist.1
  man1/aur-search.1
  man1/aur-srcver.1
  man1/aur-sync.1
  man1/aur-vercmp-devel.1
  man1/aur.1
Labels: documentation

#491 aur-repo: simplify pacman query, add -S
  lib/aur-repo
  man1/aur-repo.1
Labels: enhancement

#458 Add _aur zsh completion code
  Makefile
  completions/Makefile
  completions/bash/aurutils.in
  completions/command_opts.m4
  completions/zsh/aurutils.in
Labels: enhancement
