Repository aurutils/aurutils, pull requests merged in 2018-04, with the labels that each got.

#362 aur-build: display status on failed build
  lib/aur-build
Labels: enhancement

#374 aur-sync: --nover-shallow
  lib/aur-sync
  man1/aur-sync.1
Labels: feature

#375 contrib: Extract aur-vercmp-devel
  contrib/README.md
  contrib/aur-vercmp-devel
Labels: contrib
