Repository aurutils/aurutils, pull requests merged in 2019-12, with the labels that each got.

#649 aur-repo: add --path
  lib/aur-build
  lib/aur-repo
  lib/aur-repo-filter
  lib/aur-sync
Labels: enhancement

#650 aur-build: pass PKGDEST directly to makepkg
  lib/aur-build
Labels: enhancement

#635 aur-build: remove default arguments
  lib/aur-build
  lib/aur-fetch
  lib/aur-query
  lib/aur-repo-filter
  lib/aur-search
  lib/aur-sync
  man1/aur-build.1
  man1/aur-sync.1
Labels: enhancement

#652 aur-fetch: add --sync
  lib/aur-fetch
  lib/aur-sync
Labels: enhancement

#654 Ensure aur-repo always gets the pacman config
  lib/aur-build
  lib/aur-sync
Labels: enhancement

#640 fetch: add diff format
  lib/aur-fetch
  man1/aur-fetch.1
Labels: feature

#656 aur.1: don't make assumptions about package compression
  man1/aur.1
Labels: documentation

#657 scripts: fix use of msg/msg2
  lib/aur-build
  lib/aur-fetch
  lib/aur-repo-filter
  lib/aur-search
  lib/aur-sync
  lib/aur-vercmp
Labels: (ノಠ益ಠ)ノ彡┻━┻

#658 scripts: miscellaneous fixes
  lib/aur-build
  lib/aur-fetch
  lib/aur-repo-filter
  lib/aur-sync
  man1/aur-build.1
Labels: (ノಠ益ಠ)ノ彡┻━┻
