Repository aurutils/aurutils, pull requests merged in 2019-11, with the labels that each got.

#633 Conform to man-pages(7)
  man1/aur-build.1
  man1/aur-depends.1
  man1/aur-fetch.1
  man1/aur-graph.1
  man1/aur-pkglist.1
  man1/aur-query.1
  man1/aur-repo-filter.1
  man1/aur-repo.1
  man1/aur-search.1
  man1/aur-srcver.1
  man1/aur-sync.1
  man1/aur-vercmp.1
  man1/aur.1
  man7/aurhosting.7
  man7/aurvcs.7
Labels: documentation

#620 Use AUR_SEEN instead of AURUTILS_SEEN
  lib/aur-fetch
  man1/aur-fetch.1
Labels: feature

#639 aur-fetch: add --rebase, --results
  lib/aur-build
  lib/aur-fetch
  man1/aur-fetch.1
Labels: feature

#636 aur-fetch: unset GIT_DIR and GIT_WORK_TREE
  test/issue-636
Labels: regression-test
