Repository aurutils/aurutils, pull requests merged in 2019-03, with the labels that each got.

#538 aur-sync: add default --ignore-file location
  lib/aur-sync
  man1/aur-sync.1
Labels: enhancement

#539 aur-repo: --repo-list: use full paths instead of tsv output
  lib/aur-repo
Labels: enhancement

#540 aur.1: add custom commands
  man1/aur.1
Labels: documentation

#545 aur-chroot: add --host-conf
  lib/aur-chroot
  man1/aur-chroot.1
Labels: (ノಠ益ಠ)ノ彡┻━┻

#548 aur-fetch: remove --tar support
  lib/aur-fetch
  lib/aur-sync
  makepkg/PKGBUILD
  man1/aur-repo.1
  man1/aur-sync.1
Labels: feature

#551 aur fetch: fail if history was rewritten.
  lib/aur-fetch
Labels: enhancement
