Repository aurutils/aurutils, pull requests merged in 2019-10, with the labels that each got.

#606 aur-repo-filter: expose --sysroot
  lib/aur-repo-filter
  man1/aur-repo-filter.1
Labels: enhancement

#615 remove aur-chroot
  completions/command_opts.m4
  lib/aur-build
  lib/aur-chroot
  lib/aur-sync
  man1/aur-build.1
  man1/aur-chroot.1
  man1/aur-sync.1
  man1/aur.1
Labels: devtools

#619 man1: document pacman db size limits
  man1/aur-build.1
  man1/aur.1
Labels: upstream

#607 aur-repo: add --table
  lib/aur-repo
  man1/aur-repo.1
Labels: feature

#600 add mollyguard for aur-build/aur-sync
  lib/aur-build
  lib/aur-sync
Labels: enhancement

#601 aur-srcver: remove makepkg --log
  lib/aur-srcver
Labels: (ノಠ益ಠ)ノ彡┻━┻

#621 scripts: remove readonly variable assignments
  lib/aur-build
  lib/aur-depends
  lib/aur-fetch
  lib/aur-pkglist
  lib/aur-query
  lib/aur-repo
  lib/aur-repo-filter
  lib/aur-search
  lib/aur-srcver
  lib/aur-sync
  lib/aur-vercmp
  man1/aur.1
  man7/aurvcs.7
Labels: (ノಠ益ಠ)ノ彡┻━┻

#625 README: add rebuild-detector
  README.md
Labels: documentation

#631 aur-sync: add --provides-from, change --provides
  lib/aur-sync
  man1/aur-sync.1
Labels: enhancement

#632 move NEWS.md to aurutils.changelog
  NEWS.md
  makepkg/PKGBUILD
  makepkg/aurutils.changelog
Labels: enhancement
