Repository aurutils/aurutils, pull requests merged in 2020-02, with the labels that each got.

#666 Fix aur-build -D flag.
  lib/aur-build
  lib/aur-chroot
Labels: devtools

#675 Fix aur-fetch of more than one package
  lib/aur-fetch
Labels: (ノಠ益ಠ)ノ彡┻━┻

#684 Remove "See also" from README, add rebuild-detector to man examples
  README.md
  man1/aur-build.1
Labels: documentation

#685 Fix empty lines in ignore file
  lib/aur-sync
Labels: (ノಠ益ಠ)ノ彡┻━┻
