Repository aurutils/aurutils, pull requests merged in 2020-04, with the labels that each got.

#704 aur-sync: enable --provides by default
  lib/aur-sync
  man1/aur-sync.1
Labels: enhancement

#707 Fix "warning: 'url' requires parameter"
  lib/aur-query
  test/issue-706
Labels: (ノಠ益ಠ)ノ彡┻━┻

#708 aur-build: use --noextract for --pkgver build
  lib/aur-build
  man1/aur-build.1
Labels: enhancement

#712 aur-sync: add --rebuild-all
  lib/aur-sync
  man1/aur-sync.1
Labels: feature

#710 aur-fetch: pass on EOF to aur-depends
  lib/aur-sync
  man1/aur-sync.1
Labels: (ノಠ益ಠ)ノ彡┻━┻
