Repository aurutils/aurutils, pull requests merged in 2020-11, with the labels that each got.

#780 lib: use /tmp/aurutils/$UID for temporary files
  lib/aur-build
  lib/aur-depends
  lib/aur-query
  lib/aur-search
  lib/aur-srcver
  lib/aur-sync
  lib/aur-vercmp
Labels: (ノಠ益ಠ)ノ彡┻━┻, enhancement

#781 aur-chroot: add --create
  Makefile
  lib/aur-build
  lib/aur-chroot
  lib/aur-sync
  man1/aur-build.1
  man1/aur-chroot.1
Labels: enhancement

#786 aur-chroot: add base-devel to multilib container
  lib/aur-chroot
Labels: (ノಠ益ಠ)ノ彡┻━┻

#788 aur: add --version output
  Makefile
  aur.in
  makepkg/aurutils.changelog
Labels: enhancement

#789 aur: fix substitution of AUR_LIB_DIR
  Makefile
  aur.in
  makepkg/PKGBUILD
  makepkg/aurutils.changelog
Labels: (ノಠ益ಠ)ノ彡┻━┻

#790 aur-sync: add --provides-deep
  lib/aur-sync
  makepkg/aurutils.changelog
  man1/aur-sync.1
Labels: feature

#796 aur-build: fix db_name/db_root argument order
  lib/aur-build
  lib/aur-repo
Labels: (ノಠ益ಠ)ノ彡┻━┻
