Repository aurutils/aurutils, pull requests merged in 2020-01, with the labels that each got.

#655 scripts: readd aur-chroot
  completions/command_opts.sh
  lib/aur-build
  lib/aur-chroot
  lib/aur-sync
Labels: feature

#663 Fix building in chroot
  lib/aur-build
  lib/aur-chroot
Labels: (ノಠ益ಠ)ノ彡┻━┻

#664 aur-chroot: create automatically when necessary
  lib/aur-build
  lib/aur-chroot
Labels: enhancement

#667 Fix missing/unused flags in `aur-{build,chroot}`
  lib/aur-build
  lib/aur-chroot
Labels: (ノಠ益ಠ)ノ彡┻━┻

#670 sync: do not save state information in vifminfo
  lib/aur-sync
Labels: enhancement

#668 Run shellcheck and option parsing check on pushes and pull requests
  .github/workflows/ci.yml
  lib/aur-build
  lib/aur-chroot
  lib/aur-depends
  lib/aur-fetch
  lib/aur-pkglist
  lib/aur-query
  lib/aur-repo
  lib/aur-repo-filter
  lib/aur-search
  lib/aur-srcver
  lib/aur-sync
  lib/aur-vercmp
  test/parseopt-consistency
Labels: regression-test

#671 aur-build: fixes for #664
  lib/aur-build
  lib/aur-chroot
Labels: (ノಠ益ಠ)ノ彡┻━┻

#672 aur: respect AUR_EXEC_PATH
  Makefile
  aur.in
  man1/aur.1
Labels: enhancement
