Repository aurutils/aurutils, pull requests merged in 2020-10, with the labels that each got.

#745 aur-fetch: do not print results to stdout
  lib/aur-fetch
Labels: (ノಠ益ಠ)ノ彡┻━┻

#744 aur-build: improve "running" messages
  lib/aur-build
Labels: enhancement

#742 man1: update documentation
  man1/aur-build.1
  man1/aur-chroot.1
  man1/aur-repo-filter.1
  man1/aur-repo.1
Labels: documentation

#738 test: add package tests
  test/issue/085
  test/issue/187
  test/issue/257
  test/issue/403
  test/issue/513
  test/issue/636
  test/issue/706
  test/issue/714
  test/package-tests
Labels: regression-test

#746 aur-repo: improve status file
  lib/aur-repo
  lib/aur-sync
  man1/aur-repo.1
Labels: feature

#747 aur-fetch: do not reset if rebase.autoStash is set
  lib/aur-fetch
Labels: (ノಠ益ಠ)ノ彡┻━┻

#749 aur-build: propagate --pacman-conf to makepkg for local builds
  lib/aur-build
  lib/aur-sync
  man1/aur-build.1
  man1/aur-chroot.1
  test/package-tests
Labels: (ノಠ益ಠ)ノ彡┻━┻, upstream

#748 aur-build: do not print results to stdout
  LICENSE
  lib/aur-build
Labels: (ノಠ益ಠ)ノ彡┻━┻

#756 aur-chroot: use --update/--build
  lib/aur-build
  lib/aur-chroot
  man1/aur-chroot.1
Labels: enhancement

#758 aur-query: add AUR_QUERY_PARALLEL
  lib/aur-query
  lib/aur-search
  lib/aur-vercmp
  man1/aur-query.1
Labels: feature

#754 aur-build: support MAKEPKG environment variable
  lib/aur-build
  makepkg/PKGBUILD
  man1/aur-build.1
  man1/aur-chroot.1
Labels: enhancement

#760 aur-query: fix error reporting with AUR_QUERY_PARALLEL=1
  lib/aur-query
Labels: (ノಠ益ಠ)ノ彡┻━┻

#761 aur-build: --pacman-conf: document XDG_RUNTIME_DIR wrapper
  lib/aur-build
  man1/aur-build.1
  tests/issue/085
  tests/issue/378
  tests/issue/513
  tests/issue/714
  tests/issue/741
Labels: documentation

#755 aur-build: use libmakepkg for packagelist
  lib/aur-build
  lib/aur-chroot
  man1/aur-build.1
  man1/aur-chroot.1
Labels: enhancement

#762 README.md: add signify
  README.md
Labels: documentation

#763 aur-query: add AUR_QUERY_RPC, AUR_QUERY_RPC_SPLITNO
  lib/aur-query
  man1/aur-query.1
Labels: enhancement

#765 aurutils: add changelog for `3.0.0`
  makepkg/aurutils.changelog
  man1/aur-fetch.1
Labels: documentation

#766 aur-query: fix awk command-line
  lib/aur-build
  lib/aur-query
  tests/issue/085
  tests/issue/216
  tests/issue/378
  tests/issue/513
  tests/issue/636
  tests/issue/714
  tests/issue/741
  tests/package-test
Labels: (ノಠ益ಠ)ノ彡┻━┻

#768 aur-build.1: mention limitations of auto-key-retrieve
  man1/aur-build.1
Labels: documentation

#769 aur-sync: actually use all provides
  lib/aur-chroot
  lib/aur-sync
  makepkg/aurutils.changelog
  man1/aur-sync.1
Labels: (ノಠ益ಠ)ノ彡┻━┻

#770 aur-repo: simplify command-line
  lib/aur-repo
  man1/aur-repo.1
Labels: enhancement

#767 aur-sync: use XDG_RUNTIME_DIR for view directory
  lib/aur-sync
Labels: enhancement

#772 aurutils.changelog: release 3.0.1
  makepkg/aurutils.changelog
Labels: documentation

#774 Add --suffix option to aur sync
  lib/aur-sync
Labels: (ノಠ益ಠ)ノ彡┻━┻
