Repository aurutils/aurutils, pull requests merged in 2022-08, with the labels that each got.

#1017 lib: add `aur-fetch--mirror`
  lib/aur-fetch
  lib/aur-fetch--mirror
  makepkg/aurutils.changelog
  man1/aur-fetch.1
Labels: feature

#1016 Support extending zsh completion for third party commands
  completions/Makefile
  completions/zsh/_aur
  completions/zsh/_aur_local_packages
  completions/zsh/_aur_packages
  completions/zsh/_aur_repositories
Labels: enhancement

#1019 view: improve diagnostics, add `view-delta`
  examples/README.md
  examples/view-delta
  lib/aur-view
  makepkg/PKGBUILD
  makepkg/aurutils.changelog
  man1/aur-view.1
Labels: enhancement, examples

#1004 add `format`, `repo-parse`
  completions/command_opts.sh
  completions/zsh/_aur
  docker/Dockerfile
  examples/sync-list
  lib/aur-depends
  lib/aur-format
  lib/aur-query
  lib/aur-repo
  lib/aur-repo-parse
  lib/aur-search
  lib/aur-sync
  lib/aur-vercmp
  makepkg/PKGBUILD
  makepkg/aurutils.changelog
  man1/aur-format.1
  man1/aur-query.1
  tests/format
  tests/issue/0918
  tests/issue/0938
  tests/json/README.md
  tests/json/ascii.json
  tests/json/depends.json
  tests/json/empty.json
  tests/json/empty_a.json
  tests/json/error.json
  tests/json/meta.json
  tests/json/none.json
  tests/json/search.jsonl
  tests/json/suggests.json
  tests/json/utf-8.json
  tests/parseopt-consistency
  tests/repo-parse
Labels: enhancement, feature

#1021 build: fix `MAKEPKG`
  lib/aur-build
  man1/aur-build.1
Labels: (ノಠ益ಠ)ノ彡┻━┻

#1022 fetch: run git-checkout unconditionally with --rebase
  lib/aur-fetch
  makepkg/aurutils.changelog
  man1/aur-fetch.1
Labels: (ノಠ益ಠ)ノ彡┻━┻
