Repository aurutils/aurutils, pull requests merged in 2022-06, with the labels that each got.

#990 [Feature] Better zsh completion
  completions/Makefile
  completions/command_opts.sh
  completions/zsh/_aur.zsh
  completions/zsh/aurutils.in
Labels: enhancement

#996 search: print package name once with NO_COLOR
  lib/aur-search
Labels: (ノಠ益ಠ)ノ彡┻━┻

#1007 fetch: add --discard, run git-merge by default
  completions/zsh/_aur.zsh
  lib/aur-fetch
  lib/aur-sync
  makepkg/aurutils.changelog
  man1/aur-fetch.1
  tests/issue/0085
  tests/issue/0187
  tests/issue/0216
  tests/issue/0257
  tests/issue/0378
  tests/issue/0403
  tests/issue/0513
  tests/issue/0636
  tests/issue/0706
  tests/issue/0714
  tests/issue/0741
  tests/issue/0880
  tests/issue/0900
  tests/issue/0908
  tests/issue/0918
  tests/issue/0925
  tests/issue/0938
  tests/issue/0958
  tests/issue/1007
Labels: (ノಠ益ಠ)ノ彡┻━┻, enhancement, ┻━┻ ︵ヽ(`Д´)ﾉ︵﻿ ┻━┻
