Repository aurutils/aurutils, pull requests merged in 2022-09, with the labels that each got.

#1026 fixed manpage suggesting a wrong jq directive to parse aur query
  man1/aur.1
Labels: documentation

#1025 `chroot`: limit `sudo`-specific flags to `sudo`
  lib/aur-build--sync
  lib/aur-chroot
  makepkg/aurutils.changelog
  man1/aur-chroot.1
Labels: (ノಠ益ಠ)ノ彡┻━┻, documentation

#1027 examples: add `build-asroot`
  examples/README.md
  examples/build-asroot
  makepkg/aurutils.changelog
Labels: examples

#1029 examples: add `--sync-asroot`
  examples/README.md
  examples/build-asroot
  examples/sync-asroot
  lib/aur-build
  lib/aur-build--pkglist
  lib/aur-sync
  makepkg/aurutils.changelog
Labels: enhancement, examples

#1030 `build`: fallback to `pacman-<machine>.conf`
  lib/aur-build
  makepkg/aurutils.changelog
  man1/aur-build.1
Labels: enhancement
