Repository aurutils/aurutils, pull requests merged in 2022-03, with the labels that each got.

#949 search: set default value for empty array elements
  lib/aur-search
  makepkg/aurutils.changelog
Labels: (ノಠ益ಠ)ノ彡┻━┻, upstream

#951 chroot: do not exit on chroot creation
  lib/aur-build
  lib/aur-chroot
  makepkg/aurutils.changelog
  man1/aur-chroot.1
Labels: enhancement

#953 aurvcs.7: implement sample code with `aur-view`
  lib/aur-srcver
  makepkg/aurutils.changelog
  man7/aurvcs.7
Labels: enhancement, documentation

#954 aur-sync.1: extend description
  man1/aur-sync.1
Labels: documentation

#955 chroot: use positional arguments for packages
  lib/aur-build
  lib/aur-chroot
  makepkg/aurutils.changelog
  man1/aur-build.1
  man1/aur-chroot.1
Labels: enhancement

#957 build: allow secondary repositories for local repo sysupgrade
  lib/aur-build
  makepkg/aurutils.changelog
Labels: (ノಠ益ಠ)ノ彡┻━┻

#958 srcver: fix directory to source the build script from
  lib/aur-srcver
Labels: (ノಠ益ಠ)ノ彡┻━┻

#960 aur-fetch: handle repositories without commits
  examples/README.md
  examples/aur-sync-devel
  lib/aur-fetch
  makepkg/PKGBUILD
  man7/aurvcs.7
Labels: (ノಠ益ಠ)ノ彡┻━┻

#962 `repo`: add `--field`
  Makefile
  lib/aur-build
  lib/aur-repo
  makepkg/aurutils.changelog
  man1/aur-repo.1
Labels: feature

#963 `view`: add `--revision`, `--no-patch`
  lib/aur-view
  makepkg/aurutils.changelog
  man1/aur-view.1
Labels: enhancement

#964 examples: rewrite `sync-devel`, `sync-list`
  examples/README.md
  examples/aur-sync-devel
  examples/aur-sync-list
  examples/sync-devel
  examples/sync-list
  examples/vercmp-devel
  lib/aur-build
Labels: examples

#970 `build`: sign existing packages, `build--pkglist`
  lib/aur-build
  lib/aur-build--pkglist
Labels: enhancement

#972 `build`: add `--dry-run`
  lib/aur-build
  lib/aur-build--pkglist
  man1/aur-build.1
Labels: feature

#974 aur-sync: redirect aur-fetch output to stderr
  lib/aur-fetch
  lib/aur-sync
Labels: (ノಠ益ಠ)ノ彡┻━┻

#975 `fetch`: improve handling of existing repositories
  lib/aur-fetch
  makepkg/aurutils.changelog
Labels: enhancement

#973 examples: add `chroot-batch`
  examples/README.md
  examples/chroot-batch
  lib/aur-build
  makepkg/aurutils.changelog
Labels: enhancement, examples
