Repository aurutils/aurutils, pull requests merged in 2022-07, with the labels that each got.

#1008 fetch: improve compatibility with aurutils <=9.6
  lib/aur-fetch
  lib/aur-sync
  makepkg/aurutils.changelog
  man1/aur-fetch.1
  tests/issue/1007
Labels: enhancement

#1009 sync: use pkgspec for ignores instead of pacini
  lib/aur-sync
  makepkg/aurutils.changelog
Labels: (ノಠ益ಠ)ノ彡┻━┻, enhancement

#1010 build: do not use generated configs for elevated commands
  Makefile
  lib/aur-build
  makepkg/PKGBUILD
  makepkg/aurutils.changelog
  man1/aur-build.1
Labels: enhancement

#1013 man1, man7: fix typos
  man1/aur-build.1
  man1/aur-chroot.1
  man1/aur-fetch.1
  man1/aur-graph.1
  man1/aur-query.1
  man1/aur-repo.1
  man1/aur-sync.1
  man7/aurhosting.7
Labels: documentation

#1014 lib: add aur-build--sync helper
  lib/aur-build
  lib/aur-build--sync
  makepkg/aurutils.changelog
  man1/aur-build.1
Labels: enhancement
