Repository aurutils/aurutils, pull requests merged in 2022-04, with the labels that each got.

#977 aur-build: drop privileges with `setpriv(1)`
  Makefile
  examples/README.md
  examples/chroot-batch
  lib/aur-build
  lib/aur-repo
  makepkg/aurutils.changelog
  man1/aur-build.1
Labels: enhancement

#978 aur-build: deprecate --results, fixups
  lib/aur-build
  lib/aur-sync
  makepkg/aurutils.changelog
  man1/aur-build.1
Labels: (ノಠ益ಠ)ノ彡┻━┻

#849 Use OSC8 terminal hyperlinks in aur search
  lib/aur-search
Labels: feature

#981 aur-build: add `--results-append`, write results file as build user
  Makefile
  lib/aur-build
  makepkg/aurutils.changelog
Labels: enhancement

#982 query: support `type=suggest`
  lib/aur-query
  makepkg/aurutils.changelog
Labels: feature

#983 `aur`: load environment variables
  aur.in
  makepkg/aurutils.changelog
  man1/aur.1
Labels: feature

#987 pkglist: check local timestamp against system time
  lib/aur-pkglist
  makepkg/aurutils.changelog
  man1/aur-pkglist.1
Labels: enhancement

#986 man1: add missing options
  lib/aur-build
  lib/aur-repo
  lib/aur-repo-filter
  lib/aur-sync
  man1/aur-repo-filter.1
  man1/aur-repo.1
  man1/aur-search.1
  man1/aur-sync.1
Labels: documentation

#989 search: add --fmt-stdin
  lib/aur-search
  makepkg/aurutils.changelog
  man1/aur-search.1
Labels: enhancement

#991 search: add `--stdin-table`, rename `--fmt-stdin` -> `--stdin-json`
  lib/aur-search
  makepkg/aurutils.changelog
  man1/aur-search.1
Labels: enhancement
