Repository aurutils/aurutils, pull requests merged in 2022-02, with the labels that each got.

#900 sync: fix ignore array
  lib/aur-sync
Labels: (ノಠ益ಠ)ノ彡┻━┻

#903 sync: fix --upgrades if --ignore is specified
  lib/aur-sync
  tests/issue/741
Labels: (ノಠ益ಠ)ノ彡┻━┻, regression-test

#905 tests: add tests for issue #880, #901
  tests/issue/880
  tests/issue/901
Labels: regression-test

#910 aur-query: add HTTP POST for info-type requests
  lib/aur-query
  man1/aur-query.1
Labels: enhancement

#906 srcver: add -E / --env
  Makefile
  lib/aur-srcver
  makepkg/aurutils.changelog
Labels: feature

#913 query, pkglist: use `aurutils` user-agent
  lib/aur-pkglist
  lib/aur-query
  makepkg/aurutils.changelog
  man1/aur-query.1
Labels: enhancement

#915 aur-query: split POST requests
  lib/aur-query
  man1/aur-query.1
Labels: (ノಠ益ಠ)ノ彡┻━┻, enhancement, feature

#916 aur-repo-filter: add --config
  lib/aur-repo-filter
  lib/aur-sync
  makepkg/aurutils.changelog
  man1/aur-repo-filter.1
Labels: (ノಠ益ಠ)ノ彡┻━┻, enhancement

#919 aur-query: add set operations
  Makefile
  lib/aur-query
  lib/aur-search
  makepkg/aurutils.changelog
  man1/aur-query.1
  man1/aur-search.1
  tests/issue/880
  tests/issue/900
  tests/issue/918
Labels: (ノಠ益ಠ)ノ彡┻━┻, enhancement

#921 query: build JSON manually for union as well
  lib/aur-query
Labels: (ノಠ益ಠ)ノ彡┻━┻

#924 query: add `--raw`, intersect search results by default
  lib/aur-query
  lib/aur-search
  makepkg/aurutils.changelog
  man1/aur-query.1
  man1/aur-search.1
Labels: (ノಠ益ಠ)ノ彡┻━┻

#926 aur-query: store intermediary results
  lib/aur-query
  lib/aur-search
  tests/issue/925
Labels: (ノಠ益ಠ)ノ彡┻━┻, enhancement

#928 search: improve error handling
  lib/aur-query
  lib/aur-search
  makepkg/aurutils.changelog
  man1/aur-query.1
Labels: (ノಠ益ಠ)ノ彡┻━┻

#932 aur-pkglist: add `--verify`
  lib/aur-pkglist
  man1/aur-pkglist.1
Labels: feature

#933 aur-sync: add per-repository sections to --ignore-file
  Makefile
  lib/aur-sync
  makepkg/PKGBUILD
  makepkg/aurutils.changelog
  man1/aur-sync.1
Labels: feature

#935 depends: add --graph
  lib/aur-depends
  man1/aur-depends.1
Labels: feature

#936 depends: filter dependencies (`--no-checkdepends`) earlier
  Makefile
  lib/aur-depends
  makepkg/aurutils.changelog
  tests/package
Labels: enhancement

#934 sync: resolve dependencies with `ninja`
  Makefile
  lib/aur-depends
  lib/aur-sync
  lib/aur-sync--ninja
  makepkg/PKGBUILD
  makepkg/aurutils.changelog
  man1/aur-sync.1
  tests/parseopt-consistency
Labels: feature

#939 query: abort if no query type is specified
  lib/aur-query
  tests/issue/938
Labels: (ノಠ益ಠ)ノ彡┻━┻

#941 sync: use number of started edges
  lib/aur-sync
Labels: (ノಠ益ಠ)ノ彡┻━┻

#943 build: pass --nocheck to chroot
  lib/aur-build
Labels: (ノಠ益ಠ)ノ彡┻━┻

#944 query: avoid hardcoding request types
  lib/aur-query
  makepkg/aurutils.changelog
  man1/aur-query.1
  tests/issue/938
Labels: enhancement

#947 depends, search, sync: add `--optdepends`
  Makefile
  lib/aur-depends
  lib/aur-search
  lib/aur-sync
  makepkg/aurutils.changelog
  man1/aur-depends.1
  man1/aur-sync.1
Labels: feature
