Repository aurutils/aurutils, pull requests merged in 2023-05, with the labels that each got.

#1064 Add support to pass --no-sync option to aur-build command
  lib/aur-sync
Labels: enhancement

#1068 sync: `--rebuild-tree` implies `--no-provides`
  lib/aur-sync
Labels: (ノಠ益ಠ)ノ彡┻━┻

#1073 `chroot`: use conditional default paths
  lib/aur-chroot
  makepkg/aurutils.changelog
Labels: devtools
