Repository aurutils/aurutils, pull requests merged in 2025-09, with the labels that each got.

#1212 aur-fetch: support mixed url and pkgbase names
  lib/aurweb/aur-fetch
  tests/parseopt-consistency
Labels: enhancement

#1216 repo: avoid empty output with -q -u
  lib/pacman/aur-repo
  makepkg/aurutils.changelog
Labels: (ノಠ益ಠ)ノ彡┻━┻

#1217 `build`: add `--pool`
  lib/pacman/aur-build
  makepkg/aurutils.changelog
  man1/aur-build.1
Labels: feature

#1219 Revert "build: error on partially built package group"
  lib/pacman/aur-build
Labels: (ノಠ益ಠ)ノ彡┻━┻

#1225 chroot: preserve `SRCPKGDEST`, `MAKEFLAGS`, `PACKAGER`
  lib/pacman/aur-chroot
Labels: (ノಠ益ಠ)ノ彡┻━┻, devtools
